[theme]
base                     = "light"
primaryColor             = "#005FAD"   # deep logo blue
secondaryBackgroundColor = "#F5FAFD"   # light ice grey
textColor                = "#12213A"
font                     = "sans serif"
